file-utils: add missing include
Fixes the warning:

file-utils.c:694:9: warning: implicit declaration of function 'strcasecmp' [-Wimplicit-function-declaration]
  694 |  return strcasecmp (filename + filename_l - ext_l, ext) == 0;
      |         ^~~~~~~~~~